# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /var/www/autobuffy_backend
# hooks:
#   BeforeInstall:
#     - location: scripts/dependencies_install.sh
#       timeout: 300
#       runas: root
# file_exists_behavior: OVERWRITE
  


version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/autobuffy-be/deployment
permissions:
  - object: /var/www/autobuffy-be/deployment
    owner: ubuntu
    group: ubuntu
    pattern: "*"
    mode: 775
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: scripts/arrange_folders.sh
      runas: ubuntu
  AfterInstall:
#    - location: deployment_scripts/db-config.sh
#      runas: nginx
    - location: scripts/install-gems.sh
      runas: ubuntu
#    - location: deployment_scripts/compile-assets.sh
#      runas: nginx
#    - location: deployment_scripts/run-db-migrations.sh
#      runas: nginx

  ApplicationStart:
    - location: scripts/finish-installation.sh
      runas: ubuntu
